/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tienda.ui;

/**
 *
 * @author julio
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeskInit
     */
    public MainFrame() {
     
            
        initComponents();
     
        
        
        //setSize(800,900);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        ///com/tienda/recursos/prodcu640px.png"
        catalogo = new javax.swing.JMenu();
        ctgProducto = new javax.swing.JMenuItem();
        ctgClientes = new javax.swing.JMenuItem();
        ctgUsuario = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        transacciones = new javax.swing.JMenu();
        trsAsignacion = new javax.swing.JMenuItem();
        trsConciliacion = new javax.swing.JMenuItem();
        trsOrdenesdCompra = new javax.swing.JMenuItem();
        trsCompras = new javax.swing.JMenuItem();
        trsVentas = new javax.swing.JMenuItem();
        trsIngresoDeProducto = new javax.swing.JMenuItem();
        trsTraspaso = new javax.swing.JMenuItem();
        administracion = new javax.swing.JMenu();
        admClientes = new javax.swing.JMenuItem();
        adminProveedores = new javax.swing.JMenuItem();
        adminMovimientoDeCajas = new javax.swing.JMenuItem();
        adminCorteDCajas = new javax.swing.JMenuItem();
        adminReportes = new javax.swing.JMenuItem();
        configuracion = new javax.swing.JMenu();
        confUsuario = new javax.swing.JMenuItem();
        confAdminUsuario = new javax.swing.JMenuItem();
        confConfDDocumentos = new javax.swing.JMenuItem();
        confAcercaDe = new javax.swing.JMenuItem();
        confSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SistemControl");
        setSize(new java.awt.Dimension(600, 500));

        ///home/julio/Escritorio/Proyecto 1/Proyecto_1/Tienda/src/main/java/com/tienda/recursos/clientes32.png
        catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource(".../java/com/tienda/recursos/prodcu640px.png")));
        catalogo.setMnemonic('f');
        catalogo.setText("Catalago");

        ctgProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        ctgProducto.setMnemonic('o');
        ctgProducto.setText("Producto");
        ctgProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgProductoActionPerformed(evt);
            }
        });
        catalogo.add(ctgProducto);

        ctgClientes.setMnemonic('s');
        ctgClientes.setText("Clientes");
        catalogo.add(ctgClientes);

        ctgUsuario.setMnemonic('x');
        ctgUsuario.setText("Empleados");
        ctgUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgUsuarioActionPerformed(evt);
            }
        });
        catalogo.add(ctgUsuario);

        exit.setMnemonic('x');
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        catalogo.add(exit);

        menuBar.add(catalogo);

        transacciones.setMnemonic('e');
        transacciones.setText("Transacciones");

        trsAsignacion.setMnemonic('t');
        trsAsignacion.setText("Asignacion de Productos");
        transacciones.add(trsAsignacion);

        trsConciliacion.setMnemonic('y');
        trsConciliacion.setText("Conciliaciones");
        trsConciliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trsConciliacionActionPerformed(evt);
            }
        });
        transacciones.add(trsConciliacion);

        trsOrdenesdCompra.setMnemonic('p');
        trsOrdenesdCompra.setText("Ordenes de Compra");
        transacciones.add(trsOrdenesdCompra);

        trsCompras.setMnemonic('d');
        trsCompras.setText("Compras");
        transacciones.add(trsCompras);

        trsVentas.setMnemonic('d');
        trsVentas.setText("Ventas");
        transacciones.add(trsVentas);

        trsIngresoDeProducto.setMnemonic('d');
        trsIngresoDeProducto.setText("Ingreso de Productos");
        transacciones.add(trsIngresoDeProducto);

        trsTraspaso.setMnemonic('d');
        trsTraspaso.setText("Traspaso de Producto");
        transacciones.add(trsTraspaso);

        menuBar.add(transacciones);

        administracion.setMnemonic('h');
        administracion.setText("Administracion");

        admClientes.setMnemonic('c');
        admClientes.setText("Clientes");
        administracion.add(admClientes);

        adminProveedores.setMnemonic('a');
        adminProveedores.setText("Proveedores");
        administracion.add(adminProveedores);

        adminMovimientoDeCajas.setMnemonic('c');
        adminMovimientoDeCajas.setText("Movimiento de Caja");
        administracion.add(adminMovimientoDeCajas);

        adminCorteDCajas.setMnemonic('c');
        adminCorteDCajas.setText("Corte De Caja");
        administracion.add(adminCorteDCajas);

        adminReportes.setMnemonic('c');
        adminReportes.setText("Reportes");
        administracion.add(adminReportes);

        menuBar.add(administracion);

        configuracion.setMnemonic('e');
        configuracion.setText("Configuracion");

        confUsuario.setMnemonic('t');
        confUsuario.setText("Usuario");
        configuracion.add(confUsuario);

        confAdminUsuario.setMnemonic('y');
        confAdminUsuario.setText("Administracion de Usuarios");
        configuracion.add(confAdminUsuario);

        confConfDDocumentos.setMnemonic('p');
        confConfDDocumentos.setText("Configuracion de Documentos");
        configuracion.add(confConfDDocumentos);

        confAcercaDe.setMnemonic('d');
        confAcercaDe.setText("Acerca de...");
        configuracion.add(confAcercaDe);

        confSalir.setMnemonic('p');
        confSalir.setText("Salir");
        configuracion.add(confSalir);

        menuBar.add(configuracion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctgUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctgUsuarioActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void trsConciliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trsConciliacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trsConciliacionActionPerformed

    private void ctgProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgProductoActionPerformed
        System.out.println("Prodcuto Catalogo");
    }//GEN-LAST:event_ctgProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem admClientes;
    private javax.swing.JMenuItem adminCorteDCajas;
    private javax.swing.JMenuItem adminMovimientoDeCajas;
    private javax.swing.JMenuItem adminProveedores;
    private javax.swing.JMenuItem adminReportes;
    private javax.swing.JMenu administracion;
    private javax.swing.JMenu catalogo;
    private javax.swing.JMenuItem confAcercaDe;
    private javax.swing.JMenuItem confAdminUsuario;
    private javax.swing.JMenuItem confConfDDocumentos;
    private javax.swing.JMenuItem confSalir;
    private javax.swing.JMenuItem confUsuario;
    private javax.swing.JMenu configuracion;
    private javax.swing.JMenuItem ctgClientes;
    private javax.swing.JMenuItem ctgProducto;
    private javax.swing.JMenuItem ctgUsuario;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu transacciones;
    private javax.swing.JMenuItem trsAsignacion;
    private javax.swing.JMenuItem trsCompras;
    private javax.swing.JMenuItem trsConciliacion;
    private javax.swing.JMenuItem trsIngresoDeProducto;
    private javax.swing.JMenuItem trsOrdenesdCompra;
    private javax.swing.JMenuItem trsTraspaso;
    private javax.swing.JMenuItem trsVentas;
    // End of variables declaration//GEN-END:variables

}
