/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tienda.ui;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author julio
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeskInit
     */
    public MainFrame(boolean tipo) {

        initComponents();

        usuarioTipo(tipo);
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        
        int h = (int) screenSize.getHeight()/2;
        int w =(int) screenSize.getWidth()/2;
        this.setSize(1200,950);
        //this.setSize(screenSize);
        //setVisible(false);
         //Log log = new Log();
        //log.setVisible(true);
        //setSize(800,900);
    }
    public void usuarioTipo(boolean tipo){
        if (tipo) {
            ver.setVisible(false);
        }else{
           catalogo.setVisible(false);
           transacciones.setVisible(false);
           administracion.setVisible(false);
           configuracion.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        catalogo = new javax.swing.JMenu();
        ctgProducto = new javax.swing.JMenuItem();
        ctgClientes = new javax.swing.JMenuItem();
        ctgEmpleados = new javax.swing.JMenuItem();
        ctgTet = new javax.swing.JMenuItem();
        ctgTiendas = new javax.swing.JMenuItem();
        ctgUsuario = new javax.swing.JMenuItem();
        transacciones = new javax.swing.JMenu();
        trsAsignacion = new javax.swing.JMenuItem();
        trsOrdenesdCompra = new javax.swing.JMenuItem();
        trsVentas = new javax.swing.JMenuItem();
        trsTraspaso = new javax.swing.JMenuItem();
        administracion = new javax.swing.JMenu();
        admClientes = new javax.swing.JMenuItem();
        adminProveedores = new javax.swing.JMenuItem();
        adminMovimientoDeCajas = new javax.swing.JMenuItem();
        adminCorteDCajas = new javax.swing.JMenuItem();
        adminReportes = new javax.swing.JMenuItem();
        configuracion = new javax.swing.JMenu();
        confUsuario = new javax.swing.JMenuItem();
        confAdminUsuario = new javax.swing.JMenuItem();
        confConfDDocumentos = new javax.swing.JMenuItem();
        confAcercaDe = new javax.swing.JMenuItem();
        confSalir = new javax.swing.JMenuItem();
        ver = new javax.swing.JMenu();
        confUsuario1 = new javax.swing.JMenuItem();
        confUsuario2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SistemControl");
        setSize(new java.awt.Dimension(600, 500));

        menuBar.setBackground(new java.awt.Color(0, 153, 153));
        menuBar.setForeground(new java.awt.Color(0, 153, 153));

        catalogo.setBackground(new java.awt.Color(0, 153, 153));
        catalogo.setForeground(new java.awt.Color(0, 153, 153));
        catalogo.setMnemonic('f');
        catalogo.setText("Catalago");

        ctgProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        ctgProducto.setMnemonic('o');
        ctgProducto.setText("Producto");
        ctgProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgProductoActionPerformed(evt);
            }
        });
        catalogo.add(ctgProducto);

        ctgClientes.setMnemonic('s');
        ctgClientes.setText("Clientes");
        ctgClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgClientesActionPerformed(evt);
            }
        });
        catalogo.add(ctgClientes);

        ctgEmpleados.setMnemonic('x');
        ctgEmpleados.setText("Empleados");
        ctgEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgEmpleadosActionPerformed(evt);
            }
        });
        catalogo.add(ctgEmpleados);

        ctgTet.setMnemonic('x');
        ctgTet.setText("Tiempo Entre Tiendas");
        ctgTet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgTetActionPerformed(evt);
            }
        });
        catalogo.add(ctgTet);

        ctgTiendas.setMnemonic('x');
        ctgTiendas.setText("Tiendas");
        ctgTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgTiendasActionPerformed(evt);
            }
        });
        catalogo.add(ctgTiendas);

        ctgUsuario.setMnemonic('x');
        ctgUsuario.setText("Usuarios");
        ctgUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgUsuarioActionPerformed(evt);
            }
        });
        catalogo.add(ctgUsuario);

        menuBar.add(catalogo);

        transacciones.setBackground(new java.awt.Color(0, 153, 153));
        transacciones.setForeground(new java.awt.Color(0, 153, 153));
        transacciones.setMnemonic('e');
        transacciones.setText("Transacciones");

        trsAsignacion.setMnemonic('t');
        trsAsignacion.setText("Asignacion de Productos");
        trsAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trsAsignacionActionPerformed(evt);
            }
        });
        transacciones.add(trsAsignacion);

        trsOrdenesdCompra.setMnemonic('p');
        trsOrdenesdCompra.setText("Pedidos");
        trsOrdenesdCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trsOrdenesdCompraActionPerformed(evt);
            }
        });
        transacciones.add(trsOrdenesdCompra);

        trsVentas.setMnemonic('d');
        trsVentas.setText("Ventas");
        trsVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trsVentasActionPerformed(evt);
            }
        });
        transacciones.add(trsVentas);

        trsTraspaso.setMnemonic('d');
        trsTraspaso.setText("Tracking de Pedido");
        transacciones.add(trsTraspaso);

        menuBar.add(transacciones);

        administracion.setBackground(new java.awt.Color(0, 153, 153));
        administracion.setForeground(new java.awt.Color(0, 153, 153));
        administracion.setMnemonic('h');
        administracion.setText("Administracion");

        admClientes.setMnemonic('c');
        admClientes.setText("Clientes");
        administracion.add(admClientes);

        adminProveedores.setMnemonic('a');
        adminProveedores.setText("Usuarios");
        administracion.add(adminProveedores);

        adminMovimientoDeCajas.setMnemonic('c');
        adminMovimientoDeCajas.setText("Movimiento de Caja");
        administracion.add(adminMovimientoDeCajas);

        adminCorteDCajas.setMnemonic('c');
        adminCorteDCajas.setText("Corte De Caja");
        administracion.add(adminCorteDCajas);

        adminReportes.setMnemonic('c');
        adminReportes.setText("Reportes");
        administracion.add(adminReportes);

        menuBar.add(administracion);

        configuracion.setBackground(new java.awt.Color(0, 153, 153));
        configuracion.setForeground(new java.awt.Color(0, 153, 153));
        configuracion.setMnemonic('e');
        configuracion.setText("Configuracion");

        confUsuario.setMnemonic('t');
        confUsuario.setText("Usuario");
        configuracion.add(confUsuario);

        confAdminUsuario.setMnemonic('y');
        confAdminUsuario.setText("Administracion de Usuarios");
        configuracion.add(confAdminUsuario);

        confConfDDocumentos.setMnemonic('p');
        confConfDDocumentos.setText("Cargar Archivo");
        confConfDDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confConfDDocumentosActionPerformed(evt);
            }
        });
        configuracion.add(confConfDDocumentos);

        confAcercaDe.setMnemonic('d');
        confAcercaDe.setText("Acerca de...");
        configuracion.add(confAcercaDe);

        confSalir.setMnemonic('p');
        confSalir.setText("Salir");
        configuracion.add(confSalir);

        menuBar.add(configuracion);

        ver.setBackground(new java.awt.Color(0, 153, 153));
        ver.setForeground(new java.awt.Color(0, 153, 153));
        ver.setMnemonic('e');
        ver.setText("Ver");

        confUsuario1.setMnemonic('t');
        confUsuario1.setText("Ver Catalogo");
        ver.add(confUsuario1);

        confUsuario2.setMnemonic('t');
        confUsuario2.setText("Ver Pedidos");
        ver.add(confUsuario2);

        menuBar.add(ver);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctgEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgEmpleadosActionPerformed
        // TODO add your handling code here:
        addPanel(new EmpleadoUI());
    }//GEN-LAST:event_ctgEmpleadosActionPerformed

    private void ctgTetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgTetActionPerformed
        addPanel(new TiempoEntreTiendasUI());
    }//GEN-LAST:event_ctgTetActionPerformed

    private void ctgProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgProductoActionPerformed
        System.out.println("Prodcuto Catalogo");
        addPanel(new ProductoUI());

    }//GEN-LAST:event_ctgProductoActionPerformed

    private void confConfDDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confConfDDocumentosActionPerformed
        // TODO add your handling code here:
        
        
        addPanel(new CargarArchivoUI());

       
    }//GEN-LAST:event_confConfDDocumentosActionPerformed

    private void ctgTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgTiendasActionPerformed
        // TODO add your handling code here:
        addPanel(new TiendaUI());
    }//GEN-LAST:event_ctgTiendasActionPerformed

    private void ctgClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgClientesActionPerformed
        // TODO add your handling code here:
        addPanel(new ClienteUI());
    }//GEN-LAST:event_ctgClientesActionPerformed

    private void trsAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trsAsignacionActionPerformed
        // TODO add your handling code here:
        addPanel(new AsignacionDeProducto());
    }//GEN-LAST:event_trsAsignacionActionPerformed

    private void trsOrdenesdCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trsOrdenesdCompraActionPerformed
        // TODO add your handling code here:
        addPanel(new PedidoUI());
    }//GEN-LAST:event_trsOrdenesdCompraActionPerformed

    private void ctgUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctgUsuarioActionPerformed

    private void trsVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trsVentasActionPerformed
        // TODO add your handling code here:
        addPanel(new Ventas());
    }//GEN-LAST:event_trsVentasActionPerformed

    private void addPanel(javax.swing.JPanel panel){
        dp.removeAll();
        
        panel.setSize(dp.getWidth()/(3/2),dp.getHeight()/(3/2));
        panel.setVisible(true);
        dp.add(panel);
        

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new MainFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem admClientes;
    private javax.swing.JMenuItem adminCorteDCajas;
    private javax.swing.JMenuItem adminMovimientoDeCajas;
    private javax.swing.JMenuItem adminProveedores;
    private javax.swing.JMenuItem adminReportes;
    private javax.swing.JMenu administracion;
    private javax.swing.JMenu catalogo;
    private javax.swing.JMenuItem confAcercaDe;
    private javax.swing.JMenuItem confAdminUsuario;
    private javax.swing.JMenuItem confConfDDocumentos;
    private javax.swing.JMenuItem confSalir;
    private javax.swing.JMenuItem confUsuario;
    private javax.swing.JMenuItem confUsuario1;
    private javax.swing.JMenuItem confUsuario2;
    private javax.swing.JMenu configuracion;
    private javax.swing.JMenuItem ctgClientes;
    private javax.swing.JMenuItem ctgEmpleados;
    private javax.swing.JMenuItem ctgProducto;
    private javax.swing.JMenuItem ctgTet;
    private javax.swing.JMenuItem ctgTiendas;
    private javax.swing.JMenuItem ctgUsuario;
    public static javax.swing.JDesktopPane dp;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu transacciones;
    private javax.swing.JMenuItem trsAsignacion;
    private javax.swing.JMenuItem trsOrdenesdCompra;
    private javax.swing.JMenuItem trsTraspaso;
    private javax.swing.JMenuItem trsVentas;
    private javax.swing.JMenu ver;
    // End of variables declaration//GEN-END:variables

}
