/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tienda.ui;

import com.tienda.actiontable.DateLabelFormatter;
import com.tienda.actiontable.TableCellListener;
import com.tienda.dto.ClienteDTO;
import com.tienda.dto.ProductoTableDto;
import com.tienda.entities.Tienda;
import com.tienda.mysql.Manager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.List;
import java.util.Properties;
import java.util.Random;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author julio
 */
public final class PedidoUI extends javax.swing.JPanel {

    /**
     * Creates new form Pedido
     */
    public PedidoUI() {
        initComponents();

        manager = new Manager();
        generateCode();
        fillCombo(jCOrigen);
        fillCombo(jCDestino);
        listenerCombo();
        jCDestino.setSelectedIndex(1);
        cellListener();
        eventTableProducto();

        SeleccionarCliente.setSize(600, 400);
        SeleccionarCliente.setVisible(true);
        initDatePicker();

    }

    public void initDatePicker() {
        UtilDateModel model = new UtilDateModel();
        model.setDate(2020, 8, 1);
        Properties p = new Properties();
        p.put("text.today", "Hoy");
        p.put("text.month", "Mes");
        p.put("text.year", "Anio");
        
        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
        JDatePickerImpl datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());
        datePicker.setVisible(true);
        jPanel1.add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 210, 40));
        
        //JDatePanelImpl datePanel = new JDatePanelImpl(model);
        //JDatePanelImpl panelDate = new JDatePanelImpl(model,i18nStrings);
        //SqlDataModel sqlDataModel = new SqlDataModel();
        //JDatePanelImpl datePanel = new JDatePanelImpl(model);
        // JDatePickerImpl datePicker = new JDatePickerImpl(datePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeleccionarCliente = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnBuscarCliente = new javax.swing.JButton();
        txtBuscarCliente = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        btnAceptarCliente = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        crearCliente = new javax.swing.JDialog();
        panelContains = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCDestino = new javax.swing.JComboBox<Tienda>();
        jCOrigen = new javax.swing.JComboBox<Tienda>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCarrito = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProducto = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnFinalizarCompra = new javax.swing.JButton();
        txtCodePedido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        SeleccionarCliente.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        SeleccionarCliente.setTitle("Cliente");
        SeleccionarCliente.setModal(true);
        SeleccionarCliente.setResizable(false);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Datos Cliente"));

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCliente)
                .addGap(29, 29, 29))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nit", "Dpi", "Nombre", "Credito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableCliente);

        btnAceptarCliente.setText("Aceptar");
        btnAceptarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarClienteActionPerformed(evt);
            }
        });

        jButton8.setText("Nuevo");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Ver Todo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarCliente)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(228, 228, 228))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SeleccionarClienteLayout = new javax.swing.GroupLayout(SeleccionarCliente.getContentPane());
        SeleccionarCliente.getContentPane().setLayout(SeleccionarClienteLayout);
        SeleccionarClienteLayout.setHorizontalGroup(
            SeleccionarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SeleccionarClienteLayout.setVerticalGroup(
            SeleccionarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContainsLayout = new javax.swing.GroupLayout(panelContains);
        panelContains.setLayout(panelContainsLayout);
        panelContainsLayout.setHorizontalGroup(
            panelContainsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        panelContainsLayout.setVerticalGroup(
            panelContainsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout crearClienteLayout = new javax.swing.GroupLayout(crearCliente.getContentPane());
        crearCliente.getContentPane().setLayout(crearClienteLayout);
        crearClienteLayout.setHorizontalGroup(
            crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContains, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        crearClienteLayout.setVerticalGroup(
            crearClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContains, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tienda Origen");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 100, 38));

        jLabel2.setText("Destino");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 6, 81, 38));

        jCDestino.setEditable(true);
        jPanel1.add(jCDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 7, 237, 38));

        jCOrigen.setEditable(true);
        jPanel1.add(jCOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 7, 237, 38));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 57, 940, 20));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos En El Carrito"));

        tableCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "Precio Unitario", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCarrito.setRowHeight(40);
        jScrollPane2.setViewportView(tableCarrito);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 0, 157, 59));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 450, 420));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        tableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProducto.setRowHeight(40);
        jScrollPane1.setViewportView(tableProducto);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Ver Todo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        btnFinalizarCompra.setText("Finalizar Pedido");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraAction(evt);
            }
        });
        jPanel1.add(btnFinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 170, 50));
        jPanel1.add(txtCodePedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 250, 50));

        jLabel3.setText("Codigo De Pedido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 630, 250, 30));

        jLabel4.setText("Fecha");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 60, 30));

        jCheckBox1.setText("Hoy");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (tableCarrito.getSelectedRow() != -1) {
            ((DefaultTableModel) tableCarrito.getModel()).removeRow(tableCarrito.getSelectedRow());
            if (tableCarrito.getRowCount() != 0) {
                totalVenta();
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        translateProduct();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here
        fillTableProducto(manager.getProductoDAO().getProductoTableDto(((Tienda) jCOrigen.getSelectedItem()).getCodigo()));
    }//GEN-LAST:event_jButton6ActionPerformed

    public void listenerCombo() {
        jCOrigen.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    private void btnFinalizarCompraAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraAction
        // TODO add your handling code here:
        totalVenta();
        // com.tienda.entities.PedidoUI factura = com.tienda.entities.PedidoUI();
        //manager.getFacturaDAO().insert(factura);
        int idFactura = manager.getFacturaDAO().lastInsertId();
        //Pedido pedido = new Pedido(txtCodePedido.getText(), fecha, true, ERROR, true, true, UNDEFINED_CONDITION, nitCliente, totalPagar, totalPagar)
        if (tableCarrito.getRowCount() != 0) {
            for (int i = 0; i < tableCarrito.getRowCount(); i++) {
                /* DetalleFactura detalleFactura = new DetalleFactura(0,
                    idFactura,
                    (String) tableCarrito.getValueAt(i, 0),
                    Integer.valueOf((String)tableCarrito.getValueAt(i, 2)),
                    (BigDecimal) tableCarrito.getValueAt(i, 4));

                manager.getDetalleFacturaDAO().insert(detalleFactura);

                StockTienda st = manager.getStockTiendaDAO().existencia(Log.codigoTienda,(String) tableCarrito.getValueAt(i, 0) );

                st.setCantidad(st.getCantidad() - detalleFactura.getCantidad());
                manager.getStockTiendaDAO().modify(st);

            
            ////MetodoDePago.setSize(310, 310);
            ////MetodoDePago.setVisible(true);
                 */
            }
        }

    }//GEN-LAST:event_btnFinalizarCompraAction

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        fillTableCliente(manager.getClienteDAO().getClienteForDtoWhitLike(
                (!txtBuscarCliente.getText().isEmpty()) ? txtBuscarCliente.getText() : " "
        ));
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnAceptarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarClienteActionPerformed
        // TODO add your handling code here:
        dtCliente();
    }//GEN-LAST:event_btnAceptarClienteActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        SeleccionarCliente.dispose();
        ClienteUI crear = new ClienteUI();
        crear.setSize(800, 700);
        crear.setVisible(true);
        //crearCliente.removeAll();
        panelContains.setSize(900, 750);
        panelContains.add(crear);
        panelContains.repaint();
        panelContains.revalidate();

        crearCliente.setSize(925, 775);
        crearCliente.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        manager = new Manager();
        fillTableCliente(manager.getClienteDAO().getClienteForDto());
    }//GEN-LAST:event_jButton9ActionPerformed
    public void cellListener() {
        Action action = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                TableCellListener tcl = (TableCellListener) e.getSource();

                String codigo = (String) tableCarrito.getValueAt(tcl.getRow(), 0);
                Integer nValor = Integer.valueOf((String) tcl.getNewValue());

                if (manager.getStockTiendaDAO().existencia(Log.codigoTienda, codigo).getCantidad() <= nValor) {

                    tableCarrito.setValueAt(tcl.getOldValue(), tcl.getRow(), tcl.getColumn());
                    JOptionPane.showMessageDialog(null, "No hay Existencia Suficiente", "Cuidado", JOptionPane.WARNING_MESSAGE);

                } else {

                    BigDecimal precio = (BigDecimal) tableCarrito.getValueAt(tcl.getRow(), 3);
                    int cantidad = Integer.valueOf(String.valueOf(tcl.getNewValue()));
                    BigDecimal subTotal = precio.multiply(new BigDecimal(cantidad));
                    tableCarrito.setValueAt(subTotal, tcl.getRow(), 4);
                    totalVenta();
                }
            }
        };

        TableCellListener tcl = new TableCellListener(tableCarrito, action);
        //
    }

    private void fillCombo(JComboBox combo) {
        manager.getTiendaDAO().obtenerTodo().forEach(x -> {
            combo.addItem(x);
        });
        AutoCompleteDecorator.decorate(combo);

    }

    private void translateProduct() {
        if (tableProducto.getSelectedRow() != -1) {

            int rowSelected = tableProducto.getSelectedRow();
            Object[] object = new Object[5];
            for (int i = 0; i < 2; i++) {
                object[i] = tableProducto.getValueAt(rowSelected, i);
            }
            object[2] = 1;
            object[3] = tableProducto.getValueAt(rowSelected, 2);
            object[4] = tableProducto.getValueAt(rowSelected, 2);
            ((DefaultTableModel) tableCarrito.getModel()).addRow(object);

        }
    }

    private void fillTableProducto(List<ProductoTableDto> productos) {
        ((DefaultTableModel) tableProducto.getModel()).setRowCount(0);
        productos.forEach(producto -> {
            ((DefaultTableModel) tableProducto.getModel()).addRow(new Object[]{
                producto.getCodigo(),
                producto.getProducto(),
                producto.getPrecio(),
                producto.getCantidad()

            });
        });
    }

    public void totalVenta() {

        lblTotal.setText("Q. ");
        //   int filaSumada = 0;

        BigDecimal total = new BigDecimal(BigInteger.ZERO);

        for (int i = 0; i < tableCarrito.getRowCount(); i++) {
            total = total.add((BigDecimal) tableCarrito.getValueAt(i, 4));
            System.out.println("Total " + total);

        }
        totalPagar = total;

        lblTotal.setText("Q. " + total);
    }

    private void eventTableProducto() {
        tableProducto.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {

                if (e.getClickCount() == 2) {
                    translateProduct();
                    jCOrigen.setEnabled(false);

                }

            }
        });
    }

    public void generateCode() {
        Random rnd = new Random();
        txtCodePedido.setText("");
        for (int i = 0; i < 20; i++) {

            char c = (char) ((char) (rnd.nextInt(25)) + 65);
            txtCodePedido.setText(txtCodePedido.getText() + c);

        }
    }

    private void fillTableCliente(List<ClienteDTO> clientes) {
        ((DefaultTableModel) tableCliente.getModel()).setRowCount(0);
        clientes.forEach(x -> {
            ((DefaultTableModel) tableCliente.getModel()).addRow(new Object[]{
                x.getNit(),
                x.getDpi(),
                x.getNombre(),
                x.getCredito()
            });
        });

    }

    private void dtCliente() {
        int rowSelected = tableCliente.getSelectedRow();
        if (rowSelected != -1) {
            nitCliente = (String) tableCliente.getValueAt(rowSelected, 0);
            dpi = (String) tableCliente.getValueAt(rowSelected, 1);
            System.out.println("Cliente Seleccionado: " + nitCliente);
            SeleccionarCliente.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar A un Cliente", "Datos Clientes", JOptionPane.ERROR_MESSAGE);
        }

    }
    private String nitCliente;
    private String dpi;
    private BigDecimal totalPagar;
    private Manager manager;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog SeleccionarCliente;
    private javax.swing.JButton btnAceptarCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JDialog crearCliente;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<Tienda> jCDestino;
    private javax.swing.JComboBox<Tienda> jCOrigen;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelContains;
    private javax.swing.JTable tableCarrito;
    private javax.swing.JTable tableCliente;
    private javax.swing.JTable tableProducto;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtCodePedido;
    // End of variables declaration//GEN-END:variables
}
