/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tienda.ui;

import com.tienda.entities.Producto;
import com.tienda.mysql.Manager;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julio
 */
public class ProductoUI extends javax.swing.JPanel {

    /**
     * Creates new form CrearTienda
     */
    public ProductoUI() {
        initComponents();
        manager = new Manager();
        lblFieldCode.setVisible(false);
        lblFieldDIreccion.setVisible(false);
        lblFieldNombre.setVisible(false);
        
        buscar = "";
        evento();
        accionTable();
        actionBuscarTxt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtGarantia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVerTodo = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        lblFieldDIreccion = new javax.swing.JLabel();
        lblFieldCode = new javax.swing.JLabel();
        lblFieldNombre = new javax.swing.JLabel();

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        lblCodigo.setText("Codigo*");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        lblNombre.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        lblNombre.setText("Nombre*");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        txtNombre.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 160, 39));

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigo.setBorder(null);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 160, 39));

        lblDireccion.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        lblDireccion.setText("Fabricante*");
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 30));

        txtFabricante.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtFabricante.setForeground(new java.awt.Color(0, 0, 0));
        txtFabricante.setBorder(null);
        jPanel1.add(txtFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 166, 39));

        jLabel11.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        jLabel11.setText("Descripcion");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        txtDescripcion.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setBorder(null);
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 166, 39));

        jLabel12.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        jLabel12.setText("Garantia");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        txtGarantia.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtGarantia.setForeground(new java.awt.Color(0, 0, 0));
        txtGarantia.setBorder(null);
        jPanel1.add(txtGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 120, 39));

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Fabricante", "Descripcion", "Garantia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableView.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tableView.setRowHeight(35);
        tableView.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableView.getTableHeader().setReorderingAllowed(false);
        tableView.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tableView);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 870, 361));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 324, 50));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 324, 50));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 150, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 324, 50));

        btnVerTodo.setText("Ver Todo");
        btnVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 324, -1));

        txtSearch.setBackground(new java.awt.Color(255, 255, 255));
        txtSearch.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtSearch.setToolTipText("Buscar");
        txtSearch.setBorder(null);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 310, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 78, 180, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 180, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 340, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 160, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 120, 10));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 170, 10));

        lblFieldDIreccion.setForeground(new java.awt.Color(255, 0, 51));
        lblFieldDIreccion.setText("Campo Obligatorio");
        jPanel1.add(lblFieldDIreccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 170, -1));

        lblFieldCode.setForeground(new java.awt.Color(255, 0, 51));
        lblFieldCode.setText("Campo Obligatorio");
        jPanel1.add(lblFieldCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 170, 20));

        lblFieldNombre.setForeground(new java.awt.Color(255, 0, 51));
        lblFieldNombre.setText("Campo Obligatorio");
        jPanel1.add(lblFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        setTextField("", "", "", "", "");
        txtCodigo.setEditable(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (txtCodigo.isEditable()) {
            if (checkField()) {
                var garantiaa = (txtGarantia.getText().isEmpty()) ? "0" : txtGarantia.getText();
                Producto producto = new Producto(
                        txtCodigo.getText(),
                        txtNombre.getText(),
                        txtFabricante.getText(),
                        txtDescripcion.getText(),
                        Integer.valueOf(garantiaa), true);

                manager.getProductoDAO().insert(producto);
                JOptionPane.showMessageDialog(null, "Se Modifico Correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);

                DefaultTableModel tableModel = (DefaultTableModel) tableView.getModel();
                tableModel.addRow(new Object[]{producto.getCodigo(), producto.getNombre(), producto.getFabricante(), producto.getDescripcion(), producto.getGarantia()});

                tableModel.removeRow(row);
                setTextField("", "", "", "", "");
                txtCodigo.setEditable(false);

            }

        } else {
            if (checkField()) {
                //codigo, String nombre, String direccion, String telefono, String telefono2, String email, String horario, boolean estado) {
                if (manager.getTiendaDAO().obtener(txtCodigo.getText()) == null) {

                    Producto producto = new Producto(
                            txtCodigo.getText(),
                            txtNombre.getText(),
                            txtFabricante.getText(),
                            txtDescripcion.getText(),
                            Integer.valueOf(txtGarantia.getText()), true);

                    manager.getProductoDAO().insert(producto);
                    JOptionPane.showMessageDialog(null, "Se Ingreso Correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);

                    DefaultTableModel tableModel = (DefaultTableModel) tableView.getModel();
                    tableModel.addRow(new Object[]{producto.getCodigo(), producto.getNombre(), producto.getFabricante(), producto.getDescripcion(), producto.getGarantia()});

                    setTextField("", "", "", "", "");

                } else {
                    JOptionPane.showMessageDialog(null, "El Codigo Ingresado ya Existe", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                }
                txtCodigo.setEditable(false);
            }
        }
        txtCodigo.setEditable(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodoActionPerformed
        // TODO add your handling code here:
        Manager manager = new Manager();

        fillTable(manager.getProductoDAO().obtenerTodo());


    }//GEN-LAST:event_btnVerTodoActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        //fillTable(manager.getTiendaDAO().getSearchWithLike(txtSearch.getText()));
        evento();


    }//GEN-LAST:event_txtSearchActionPerformed

    public void fillTable(List<Producto> listadoTienda) {
        DefaultTableModel tableModel = (DefaultTableModel) tableView.getModel();
        tableModel.setNumRows(0);

        listadoTienda.forEach(tiendax -> {
            tableModel.addRow(new Object[]{
                tiendax.getCodigo(),
                tiendax.getNombre(),
                tiendax.getFabricante(),
                tiendax.getDescripcion(),
                tiendax.getGarantia(),});
        });

        tableView.setModel(tableModel);

    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(null, "Seguro que desea elimiar El Producto\n Codigo " + txtCodigo.getText() + "con Nombre: " + txtNombre.getText(), "Advertencia", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE) == 0) {
//            Tienda tienda = new Tienda(codigo, nombre, direccion, telefono, telefono2, email, horario, false);
//            manager.getTiendaDAO().modify(tienda);
//            DefaultTableModel model = (DefaultTableModel) tableView.getModel();
//            model.removeRow(row);

            Producto producto = new Producto(codigo, nombre, fabricante, descripcion, garantia, false);
            //setTextField("", "", "", "", "", "", "");
            JOptionPane.showMessageDialog(null, "Eliminacion exitosa", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        fillTable(manager.getProductoDAO().getSearchWithLike(txtSearch.getText()));
    }//GEN-LAST:event_btBuscarActionPerformed
 private void actionBuscarTxt() {
        txtSearch.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                fillTable(manager.getProductoDAO().getSearchWithLike(txtSearch.getText()));
            }

        });
    }
    private void accionTable() {
        tableView.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                row = tableView.rowAtPoint(evt.getPoint());
                int col = tableView.columnAtPoint(evt.getPoint());

                codigo = (String) tableView.getModel().getValueAt(row, 0);
                nombre = (String) tableView.getModel().getValueAt(row, 1);
                descripcion = (String) tableView.getModel().getValueAt(row, 2);
                fabricante = (String) tableView.getModel().getValueAt(row, 3);
                garantia = (int) tableView.getModel().getValueAt(row, 4);
                System.out.println("Codigo" + codigo);

                setTextField(codigo, nombre, descripcion, fabricante, String.valueOf(garantia));
            }
        });

    }

    private boolean checkField() {
        lblFieldCode.setVisible(txtCodigo.getText().isEmpty());
        lblFieldDIreccion.setVisible(txtFabricante.getText().isEmpty());
        lblFieldNombre.setVisible(txtNombre.getText().isEmpty());

        return !txtCodigo.getText().isEmpty()
                && !txtFabricante.getText().isEmpty()
                && !txtNombre.getText().isEmpty();

    }

    private void setTextField(String codigo, String nombre, String direccion, String descripcion, String horario) {
        txtCodigo.setText(codigo);
        txtNombre.setText(nombre);
        txtFabricante.setText(direccion);

        txtDescripcion.setText(descripcion);
        txtGarantia.setText(horario);
    }

    public void evento() {
        txtSearch.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verificar si la tecla pulsada no es un digito
                buscar += caracter; 
               fillTable(manager.getProductoDAO().getSearchWithLike(buscar));
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    e.consume();  // ignorar el evento de teclado
                }
            }
        });
    }
    private int row;

    private Manager manager;
    private String codigo;
    private String nombre;
    private String descripcion;
    private String fabricante;
    private int garantia;
    private String buscar;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVerTodo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFieldCode;
    private javax.swing.JLabel lblFieldDIreccion;
    private javax.swing.JLabel lblFieldNombre;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tableView;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
