/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tienda.ui;

import com.tienda.entities.Tienda;
import com.tienda.mysql.Manager;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julio
 */
public class TiendaUI extends javax.swing.JPanel {

    /**
     * Creates new form CrearTienda
     */
    public TiendaUI() {
        initComponents();
        manager = new Manager();
        lblFieldCode.setVisible(false);
        lblFieldDIreccion.setVisible(false);
        lblFieldNombre.setVisible(false);
        lblFieldTelefono.setVisible(false);
        accionTable();
        actionBuscarTxt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefono2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtHorario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVerTodo = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        lblFieldDIreccion = new javax.swing.JLabel();
        lblFieldCode = new javax.swing.JLabel();
        lblFieldNombre = new javax.swing.JLabel();
        lblFieldTelefono = new javax.swing.JLabel();

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tienda"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        lblCodigo.setText("Codigo*");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 54, -1, -1));

        lblNombre.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        lblNombre.setText("Nombre*");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        txtNombre.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 42, 160, 39));

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigo.setBorder(null);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 42, 160, 39));

        lblDireccion.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        lblDireccion.setText("Direccion*");
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion.setBorder(null);
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 116, 166, 39));

        lblTelefono.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        lblTelefono.setText("Telefono*");
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setBorder(null);
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 116, 166, 39));

        jLabel10.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        jLabel10.setText("Tlefono 2");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 203, -1, -1));

        txtTelefono2.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtTelefono2.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono2.setBorder(null);
        txtTelefono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefono2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 191, 160, 39));

        jLabel11.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        jLabel11.setText("Email");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        txtEmail.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 191, 166, 39));

        jLabel12.setFont(new java.awt.Font("Fira Code Light", 2, 16)); // NOI18N
        jLabel12.setText("Horario");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 277, -1, -1));

        txtHorario.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtHorario.setForeground(new java.awt.Color(0, 0, 0));
        txtHorario.setBorder(null);
        jPanel1.add(txtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 329, 39));

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Direccion", "Telefono", "Telefono 2", "Correo Electronico", "Horario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableView.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tableView.setRowHeight(30);
        tableView.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableView.getTableHeader().setReorderingAllowed(false);
        tableView.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tableView);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 870, 361));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 324, 50));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 324, 50));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 150, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 324, 50));

        btnVerTodo.setText("Ver Todo");
        btnVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 324, -1));

        txtSearch.setBackground(new java.awt.Color(255, 255, 255));
        txtSearch.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N
        txtSearch.setToolTipText("Buscar");
        txtSearch.setBorder(null);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 310, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 160, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 78, 180, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 82, 180, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 180, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 340, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 160, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 320, 10));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 170, 10));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 180, 10));

        lblFieldDIreccion.setForeground(new java.awt.Color(255, 0, 51));
        lblFieldDIreccion.setText("Campo Obligatorio");
        jPanel1.add(lblFieldDIreccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 170, -1));

        lblFieldCode.setForeground(new java.awt.Color(255, 0, 51));
        lblFieldCode.setText("Campo Obligatorio");
        jPanel1.add(lblFieldCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 170, 20));

        lblFieldNombre.setForeground(new java.awt.Color(255, 0, 51));
        lblFieldNombre.setText("Campo Obligatorio");
        jPanel1.add(lblFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 170, -1));

        lblFieldTelefono.setForeground(new java.awt.Color(255, 0, 51));
        lblFieldTelefono.setText("Campo Obligatorio");
        jPanel1.add(lblFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        setTextField("", "", "", "", "", "", "");
        txtCodigo.setEditable(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (txtCodigo.isEditable()) {
            if (checkField()) {
                Tienda tienda = new Tienda(
                        txtCodigo.getText(),
                        txtNombre.getText(),
                        txtDireccion.getText(),
                        txtTelefono.getText(),
                        txtTelefono2.getText(),
                        txtEmail.getText(),
                        txtHorario.getText(), true);

                manager.getTiendaDAO().insert(tienda);
                JOptionPane.showMessageDialog(null, "Se Modifico Correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);

                DefaultTableModel tableModel = (DefaultTableModel) tableView.getModel();
                tableModel.addRow(new Object[]{tienda.getCodigo(), tienda.getNombre(), tienda.getDireccion(), tienda.getTelefono(), tienda.getTelefono2(), tienda.getEmail(), tienda.getHorario()});

                tableModel.removeRow(row);
                setTextField("", "", "", "", "", "", "");

            }

        } else {
            if (checkField()) {
                //codigo, String nombre, String direccion, String telefono, String telefono2, String email, String horario, boolean estado) {
                if (manager.getTiendaDAO().obtener(txtCodigo.getText()) == null) {

                    Tienda tienda = new Tienda(
                            txtCodigo.getText(),
                            txtNombre.getText(),
                            txtDireccion.getText(),
                            txtTelefono.getText(),
                            txtTelefono2.getText(),
                            txtEmail.getText(),
                            txtHorario.getText(), true);

                    manager.getTiendaDAO().insert(tienda);
                    JOptionPane.showMessageDialog(null, "Se Ingreso Correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);

                    DefaultTableModel tableModel = (DefaultTableModel) tableView.getModel();
                    tableModel.addRow(new Object[]{tienda.getCodigo(), tienda.getNombre(), tienda.getDireccion(), tienda.getTelefono(), tienda.getTelefono2(), tienda.getEmail(), tienda.getHorario()});

                    setTextField("", "", "", "", "", "", "");

                } else {
                    JOptionPane.showMessageDialog(null, "El Codigo Ingresado ya Existe", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        txtCodigo.setEditable(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodoActionPerformed
        // TODO add your handling code here:
        Manager manager = new Manager();

        fillTable(manager.getTiendaDAO().obtenerTodo());


    }//GEN-LAST:event_btnVerTodoActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        fillTable(manager.getTiendaDAO().getSearchWithLike(txtSearch.getText()));

    }//GEN-LAST:event_txtSearchActionPerformed

    public void fillTable(List<Tienda> listadoTienda) {
        DefaultTableModel tableModel = (DefaultTableModel) tableView.getModel();
        tableModel.setNumRows(0);

        listadoTienda.forEach(tiendax -> {
            tableModel.addRow(new Object[]{
                tiendax.getCodigo(),
                tiendax.getNombre(),
                tiendax.getDireccion(),
                tiendax.getTelefono(),
                tiendax.getTelefono2(),
                tiendax.getEmail(),
                tiendax.getHorario()});
        });

        tableView.setModel(tableModel);

    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(null, "Seguro que desea elimiar la tienda\n Codigo " + txtCodigo.getText() + "con Nombre: " + txtNombre.getText(), "Advertencia", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE) == 0) {
            Tienda tienda = new Tienda(codigo, nombre, direccion, telefono, telefono2, email, horario, false);
            manager.getTiendaDAO().modify(tienda);
            DefaultTableModel model = (DefaultTableModel) tableView.getModel();
            model.removeRow(row);
            setTextField("", "", "", "", "", "", "");
            JOptionPane.showMessageDialog(null, "Eliminacion exitosa", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtTelefono2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefono2ActionPerformed

    }//GEN-LAST:event_txtTelefono2ActionPerformed

    private void actionBuscarTxt() {
        txtSearch.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                fillTable(manager.getTiendaDAO().getSearchWithLike(txtSearch.getText()));
            }

        });
    }
    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:

        fillTable(manager.getTiendaDAO().getSearchWithLike(txtSearch.getText()));
    }//GEN-LAST:event_btBuscarActionPerformed

    private void accionTable() {
        tableView.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                row = tableView.rowAtPoint(evt.getPoint());
                int col = tableView.columnAtPoint(evt.getPoint());

                codigo = (String) tableView.getModel().getValueAt(row, 0);
                nombre = (String) tableView.getModel().getValueAt(row, 1);
                direccion = (String) tableView.getModel().getValueAt(row, 2);
                telefono = (String) tableView.getModel().getValueAt(row, 3);
                telefono2 = (String) tableView.getModel().getValueAt(row, 4);
                email = (String) tableView.getModel().getValueAt(row, 5);
                horario = (String) tableView.getModel().getValueAt(row, 6);
                System.out.println("Codigo" + codigo);

                setTextField(codigo, nombre, direccion, telefono, telefono2, email, horario);
            }
        });

    }

    private boolean checkField() {
        lblFieldCode.setVisible(txtCodigo.getText().isEmpty());
        lblFieldDIreccion.setVisible(txtDireccion.getText().isEmpty());
        lblFieldNombre.setVisible(txtNombre.getText().isEmpty());
        lblFieldTelefono.setVisible(txtTelefono.getText().isEmpty());

        return !txtCodigo.getText().isEmpty()
                && !txtDireccion.getText().isEmpty()
                && !txtNombre.getText().isEmpty()
                && !txtTelefono.getText().isEmpty();

    }

    private void setTextField(String codigo, String nombre, String direccion, String telefono, String telefono2, String email, String horario) {
        txtCodigo.setText(codigo);
        txtNombre.setText(nombre);
        txtDireccion.setText(direccion);
        txtTelefono.setText(telefono);
        txtTelefono2.setText(telefono2);
        txtEmail.setText(email);
        txtHorario.setText(horario);
    }
    private int row;

    private Manager manager;
    private String codigo;
    private String nombre;
    private String direccion;
    private String telefono;
    private String telefono2;
    private String email;
    private String horario;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVerTodo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFieldCode;
    private javax.swing.JLabel lblFieldDIreccion;
    private javax.swing.JLabel lblFieldNombre;
    private javax.swing.JLabel lblFieldTelefono;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTable tableView;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono2;
    // End of variables declaration//GEN-END:variables
}
