/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tienda.reporte.ui;

import com.tienda.dto.ClienteDTO;
import com.tienda.dto.DetallePedidoProducto;
import com.tienda.dto.FacturaDto;
import com.tienda.entities.Cliente;
import com.tienda.entities.Persona;
import com.tienda.mysql.Manager;
import com.tienda.reporte.BodyHtml;
import com.tienda.reporte.EncabezoHtml;
import com.tienda.reporte.ParrafoHtml;
import com.tienda.reporte.ParseHtml;
import com.tienda.reporte.TablaHtml;
import com.tienda.reporte.TituloHTML;
import com.tienda.ui.Log;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julio
 */
public class ComprasCliente extends javax.swing.JPanel {

    /**
     * Creates new form ComprasCliente
     */
    public ComprasCliente() {
        initComponents();
        eventTableCliente();
        eventTablePrincipal();
        manager = new Manager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDatosTienda = new javax.swing.JLabel();
        txtDateFinal = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePrincipal = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDescripcion = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnBuscarCliente = new javax.swing.JButton();
        txtBuscarCliente = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        btnAceptarCliente = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtDateInit = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte de  Compras por un Cliente"));

        txtDateFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        tablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Tienda", "identificador Compra", "Total", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePrincipal);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tableDescripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableDescripcion);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Datos Cliente"));

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCliente)
                .addGap(29, 29, 29))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nit", "Dpi", "Nombre", "Credito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableCliente);

        btnAceptarCliente.setText("Aceptar");
        btnAceptarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarClienteActionPerformed(evt);
            }
        });

        jButton9.setText("Ver Todo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarCliente)
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtDateInit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel2.setText("Del");

        jLabel1.setText("al");

        jLabel3.setText("Rango De Fechas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(72, 72, 72)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDateInit, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(lblDatosTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDatosTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2)
                                .addComponent(txtDateInit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.reporte = null;       
        
        if (nitCliente == null) {
            JOptionPane.showMessageDialog(null, "Debe De Seleccionar un Cliente","Informacion",JOptionPane.INFORMATION_MESSAGE);
        }else{
            this.reporte = new ArrayList<>();
            System.out.println("Traer datos");
            datos();
            verificar();
        }

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed

        fillTableCliente(manager.getClienteDAO().getClienteForDtoWhitLike(
                (!txtBuscarCliente.getText().isEmpty()) ? txtBuscarCliente.getText() : " "
        ));
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnAceptarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarClienteActionPerformed

        dtCliente();
    }//GEN-LAST:event_btnAceptarClienteActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        fillTableCliente(manager.getClienteDAO().getClienteForDto());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tablePrincipal.getRowCount() > 0) {
            Guardar ruta = new Guardar();
            String path = ruta.guardarEn();
            JTextArea area = new JTextArea();
            armarReporte(area);
            ParseHtml crearHtml = new ParseHtml();
            crearHtml.imprimirReporte(path, area, "Compras Por Un Cliente " + LocalDate.now());
            JOptionPane.showMessageDialog(null, "Documento Generado Exitosamente", "Informacion",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Documento con 0 datos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void datos(){
        LocalDate dateInit;
        LocalDate dateFinal;
        java.sql.Date inicio = null;
        java.sql.Date fechaFinal = null;
        
        if (!txtDateInit.getText().isEmpty()) {
            String[] date = txtDateInit.getText().split("/");
            dateInit = LocalDate.of(Integer.valueOf(date[2]), Integer.valueOf(date[1]), Integer.valueOf(date[0]));
            inicio = java.sql.Date.valueOf(dateInit);
            
        }
        if (!txtDateFinal.getText().isEmpty()) {
            String[] date = txtDateFinal.getText().split("/");
            dateFinal = LocalDate.of(Integer.valueOf(date[2]), Integer.valueOf(date[1]), Integer.valueOf(date[0]));
            fechaFinal = java.sql.Date.valueOf(dateFinal);
        }
        reporte.addAll(manager.getFacturaDAO().reporteCinco(nitCliente, Log.codigoTienda, inicio, fechaFinal));
        //java.sql.Date.valueOf(dateInit);
        verificar();
        
    }
    public void verificar() {

        if (reporte.size() != 0) {

            fillTable(reporte);
        } else {
            JOptionPane.showMessageDialog(null, "No Hay Datos Para Mostrar", "informacion", JOptionPane.INFORMATION_MESSAGE);

        }
    }

    public void eventTablePrincipal() {
        tablePrincipal.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                System.out.println("Event Realse");
                if (e.getKeyCode() == KeyEvent.VK_UP || e.getKeyCode() == KeyEvent.VK_DOWN) {
                    descripcionPedido = new ArrayList<>();
                    String codigoPedido = (String) tablePrincipal.getValueAt(tablePrincipal.getSelectedRow(), 2);
                    descripcionPedido.addAll(manager.getDetalleFacturaDAO().getCodigoProductoCantidad(codigoPedido));
                    fillTableDescripcion(descripcionPedido);
                }
            }

        });
    }

    public void fillTableDescripcion(List<DetallePedidoProducto> detalles) {
        ((DefaultTableModel) tableDescripcion.getModel()).setRowCount(0);
        detalles.forEach(x -> {
            ((DefaultTableModel) tableDescripcion.getModel()).addRow(new Object[]{
                x.getCodigo(),
                x.getProducto(),
                x.getCantidad()

            });
        }
        );

    }

    public void fillTable(List<FacturaDto> pedidosEnTransito) {
        ((DefaultTableModel) tablePrincipal.getModel()).setRowCount(0);

        pedidosEnTransito.forEach(pedido -> {
            ((DefaultTableModel) tablePrincipal.getModel()).addRow(new Object[]{
                pedido.getCodigoTienda(),
                pedido.getTienda(),
                pedido.getIdFactura(),
                pedido.getTotal(),
                pedido.getFecha(),
            });
        });

    }

    public void buscar() {
        if (txtBuscarCliente.getText().isEmpty()) {
            fillTableCliente(manager.getClienteDAO().getClienteForDto());
        } else {
            fillTableCliente(manager.getClienteDAO().getClienteForDtoWhitLike(txtBuscarCliente.getText()));
        }
    }

    private void fillTableCliente(List<ClienteDTO> clientes) {
        ((DefaultTableModel) tableCliente.getModel()).setRowCount(0);
        clientes.forEach(x -> {
            ((DefaultTableModel) tableCliente.getModel()).addRow(new Object[]{
                x.getNit(),
                x.getDpi(),
                x.getNombre(),
                x.getCredito()
            });
        });

    }

    private void eventTableCliente() {
        tableCliente.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                //super.mouseClicked(e); //To change body of generated methods, choose Tools | Templates.
                if (e.getClickCount() == 2) {
                    dtCliente();

                }
            }

        });
    }

    private void dtCliente() {
        int rowSelected = tableCliente.getSelectedRow();
        if (rowSelected != -1) {
            nitCliente = (String) tableCliente.getValueAt(rowSelected, 0);
            dpi = (String) tableCliente.getValueAt(rowSelected, 1);
            System.out.println("Cliente Seleccionado: " + nitCliente);

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar A un Cliente", "Datos Clientes", JOptionPane.ERROR_MESSAGE);
        }

    }

     
    public void armarParrafo() {

        for (int i = 0; i < tablePrincipal.getRowCount(); i++) {

            String[] descripcion = new String[5];
            String codigoPedido = (String) tablePrincipal.getValueAt(i, 2);
            
            armarTablas(manager.getDetallePedidoDAO().getCodigoProductoCantidad(codigoPedido));
            
            descripcion[0] ="Codigo De Tienda: "+ (String) tablePrincipal.getValueAt(i, 0);
            descripcion[1] ="Tienda Origen: " +  (String) tablePrincipal.getValueAt(i, 1);
            descripcion[2] = "Identificador De Compra: "+(String) tablePrincipal.getValueAt(i, 2);
            descripcion[3] = "Total: "+(String) tablePrincipal.getValueAt(i, 3);
            descripcion[4] = "Fecha: "+(String) tablePrincipal.getValueAt(i, 4);

            
            parrafosList.add(descripcion);
        }

    }

    public void armarTablas(List<DetallePedidoProducto> filasTabla) {
        for (int i = 0; i < filasTabla.size(); i++) {
            String[][] tabla = new String[filasTabla.size()][3];

            tabla[i][0] = filasTabla.get(i).getCodigo();
            tabla[i][1] = filasTabla.get(i).getProducto();
            tabla[i][2] = String.valueOf(filasTabla.get(i).getCantidad());

            tablasList.add(tabla);

        }
    }

    public void armarReporte(JTextArea area) {
        armarParrafo();

        Cliente cliente = manager.getClienteDAO().obtener(nitCliente);
       Persona persona = manager.getPersonaDAO().obtener(cliente.getPersona_dpi());

        EncabezoHtml encabezado = new EncabezoHtml("Pedidos De un Clinete");
        encabezado.imprimirEncabezado(area);

        BodyHtml body = new BodyHtml();
        body.openBody(area);

        TituloHTML tituloHTML = new TituloHTML(2);
        tituloHTML.imprimirTitulo(area, "Compras Del Cliente: "+persona.getNombre()+" Nit:"+cliente.getNit());
        System.out.println(tablePrincipal.getRowCount() + "===>");

        for (int i = 0; i < tablePrincipal.getRowCount(); i++) {

            ParrafoHtml parrafoHtml = new ParrafoHtml(parrafosList.get(i));
            parrafoHtml.printParrafo(area);
            TablaHtml tablaHtml = new TablaHtml(tablasList.get(i), 3, "Codigo", "Producto ", " Cantidad");
            tablaHtml.imprimirTabla(area);

        }
        body.cerrarBody(area);

    }

    
    private List<String[][]> tablasList = new ArrayList<>();
    private List<String[]> parrafosList = new ArrayList<>();;
   
    private String nitCliente;
    private String dpi;

    private Manager manager;
    private List<FacturaDto> reporte;
    private List<DetallePedidoProducto> descripcionPedido;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDatosTienda;
    private javax.swing.JTable tableCliente;
    private javax.swing.JTable tableDescripcion;
    private javax.swing.JTable tablePrincipal;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JFormattedTextField txtDateFinal;
    private javax.swing.JFormattedTextField txtDateInit;
    // End of variables declaration//GEN-END:variables
}
