/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tienda.reporte.ui;

import com.tienda.dto.DetallePedidoProducto;
import com.tienda.dto.FacturaDto;
import com.tienda.entities.Cliente;
import com.tienda.entities.Persona;
import com.tienda.mysql.Manager;
import com.tienda.reporte.BodyHtml;
import com.tienda.reporte.EncabezoHtml;
import com.tienda.reporte.ParrafoHtml;
import com.tienda.reporte.ParseHtml;
import com.tienda.reporte.TablaHtml;
import com.tienda.reporte.TituloHTML;
import com.tienda.ui.Log;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julio
 */
public class MasVendido extends javax.swing.JPanel {

    /**
     * Creates new form MasVendido
     */
    public MasVendido(boolean withTienda) {
        initComponents();
        this.conTienda = withTienda;
        if (withTienda) {
            lblDatosTienda.setText("Codigo: " + Log.codigoTienda + " Tienda: " + Log.nombreTienda);
        } else {
            lblDatosTienda.setText("Mas Vendidos De Todas Las Tiendas ");
        }

        manager = new Manager();
        this.reporte = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePrincipal = new javax.swing.JTable();
        txtDateInit = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDateFinal = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDatosTienda = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("10 Productos Mas Vendidos"));

        tablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePrincipal);

        txtDateInit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel2.setText("Del");

        txtDateFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Rango De Fechas");

        jLabel1.setText("al");

        lblDatosTienda.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        lblDatosTienda.setForeground(new java.awt.Color(102, 102, 255));

        jButton1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(txtDateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDateInit, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(lblDatosTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblDatosTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)
                        .addComponent(txtDateInit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        datos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tablePrincipal.getRowCount() > 0) {
            Guardar ruta = new Guardar();
            String path = ruta.guardarEn();
            JTextArea area = new JTextArea();
            armarReporte(area);
            ParseHtml crearHtml = new ParseHtml();
            crearHtml.imprimirReporte(path, area, "Productos Mas Vendidos " + LocalDate.now());
            JOptionPane.showMessageDialog(null, "Documento Generado Exitosamente", "Informacion",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Documento con 0 datos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void datos() {

        System.out.println("Datos == >");
        LocalDate dateInit;
        LocalDate dateFinal;
        java.sql.Date inicio = null;
        java.sql.Date fechaFinal = null;

        if (!txtDateInit.getText().isEmpty()) {
            String[] date = txtDateInit.getText().split("/");
            dateInit = LocalDate.of(Integer.valueOf(date[2]), Integer.valueOf(date[1]), Integer.valueOf(date[0]));
            inicio = java.sql.Date.valueOf(dateInit);

        }
        if (!txtDateFinal.getText().isEmpty()) {
            String[] date = txtDateFinal.getText().split("/");
            dateFinal = LocalDate.of(Integer.valueOf(date[2]), Integer.valueOf(date[1]), Integer.valueOf(date[0]));
            fechaFinal = java.sql.Date.valueOf(dateFinal);
        }

        if (conTienda) {
            reporte.addAll(manager.getDetalleFacturaDAO().reporteOcho(Log.codigoTienda, inicio, fechaFinal));
        } else {
            reporte.addAll(manager.getDetalleFacturaDAO().reporteSiete(inicio, fechaFinal));

        }
        //java.sql.Date.valueOf(dateInit);
        verificar();

    }

    public void verificar() {
        System.out.println("Verificar");
        if (reporte.size() != 0) {

            fillTable(reporte);
        } else {
            JOptionPane.showMessageDialog(null, "No Hay Datos Para Mostrar", "informacion", JOptionPane.INFORMATION_MESSAGE);

        }
        System.out.println("Reportte sixze" + reporte.size());
    }

    public void fillTable(List<DetallePedidoProducto> detalles) {
        ((DefaultTableModel) tablePrincipal.getModel()).setRowCount(0);
        detalles.forEach(x -> {
            ((DefaultTableModel) tablePrincipal.getModel()).addRow(new Object[]{
                x.getCodigo(),
                x.getProducto(),
                x.getCantidad()

            });
        }
        );

    }

    public void armarParrafo() {

        String[] descripcion = new String[3];

        descripcion[0] = "Listado de los 10: ";
        descripcion[1] = "Productos mas Vendidos";

        if (conTienda) {

            descripcion[2] = "En La Tienda: " + Log.nombreTienda;
        } else {

            descripcion[2] = "De todas las Tiendas";
        }

        parrafosList.add(descripcion);
        
        List<DetallePedidoProducto> filasTabla = new ArrayList<>(); 
        for (int i = 0; i < tablePrincipal.getRowCount(); i++) {
            String codigo = (String) tablePrincipal.getValueAt(i, 0);
            String producto = (String) tablePrincipal.getValueAt(i, 1);
            int cantidad = Integer.valueOf((String)tablePrincipal.getValueAt(i, 2));
            filasTabla.add(new DetallePedidoProducto(codigo, producto, cantidad));
            
        }

    }

    public void armarTablas(List<DetallePedidoProducto> filasTabla) {
        for (int i = 0; i < filasTabla.size(); i++) {
            String[][] tabla = new String[filasTabla.size()][3];

            tabla[i][0] = filasTabla.get(i).getCodigo();
            tabla[i][1] = filasTabla.get(i).getProducto();
            tabla[i][2] = String.valueOf(filasTabla.get(i).getCantidad());

            tablasList.add(tabla);

        }
    }

    public void armarReporte(JTextArea area) {
        armarParrafo();

        //Cliente cliente = manager.getClienteDAO().obtener(nitCliente);
        //Persona persona = manager.getPersonaDAO().obtener(cliente.getPersona_dpi());
        EncabezoHtml encabezado = new EncabezoHtml("Pedidos De un Clinete");
        encabezado.imprimirEncabezado(area);

        BodyHtml body = new BodyHtml();
        body.openBody(area);

        TituloHTML tituloHTML = new TituloHTML(2);
        tituloHTML.imprimirTitulo(area, "Productos Mas Vendidos");
        System.out.println(tablePrincipal.getRowCount() + "===>");

        for (int i = 0; i < tablePrincipal.getRowCount(); i++) {

            ParrafoHtml parrafoHtml = new ParrafoHtml(parrafosList.get(i));
            parrafoHtml.printParrafo(area);
            TablaHtml tablaHtml = new TablaHtml(tablasList.get(i), 3, "Codigo", "Producto ", " Cantidad");
            tablaHtml.imprimirTabla(area);

        }
        body.cerrarBody(area);

    }

    private List<String[][]> tablasList = new ArrayList<>();
    private List<String[]> parrafosList = new ArrayList<>();
    ;
   
    private Manager manager;
    private List<DetallePedidoProducto> reporte;
    private boolean conTienda;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatosTienda;
    private javax.swing.JTable tablePrincipal;
    private javax.swing.JFormattedTextField txtDateFinal;
    private javax.swing.JFormattedTextField txtDateInit;
    // End of variables declaration//GEN-END:variables
}
